# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Gradle
      run: ./gradlew build

    - name: Build with Maven
      run: mvn install:install-file -DgroupId=com.github.chrisofnormandy -DartifactId=conlib -Dversion=$1 -Dfile=build/libs/conlib-$1.jar -Dpackaging=jar -DlocalRepositoryPath=. -DcreateChecksum=true -Djar.finalName=${artifactId}-${version}

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/.m2/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}